import enum


class MongoCollections(str, enum.Enum):
    quotes = 'quotes'  # Raw quotes are fetched by Vanessa Huxtable and pushed into this collection
    graphs = 'graphs'  # Graphs are generated by Denise Huxtable and delivered by the Dabnis REST API


class SecurityType(str, enum.Enum):
    """ BOND, EQ, INDX, MF, MMF, OPTN """

    bond = 'BOND'
    equity = 'EQ'
    index = 'INDX'
    mutual_fund = 'MF'
    money_market_fund = 'MMF'
    option = 'OPTN'


class OptionType(str, enum.Enum):
    call = 'CALL'
    put = 'PUT'
    none = 'N/A'


class TradeAction(str, enum.Enum):
    buy = 'BUY'
    sell = 'SELL'
